### ISSUE TITLE
No photos

### ISSUE THREAD

**Issue by marcza71** [stuporglue/fastback#2]
Good morning. Please help. My photos aren't showing up, a message pops up. Greetings, Marek
No photos are available for this view. Try changing your filters.A new install will need a few minutes to populate the database.
Greetings, Marek.

**Comment by stuporglue** [comment]
Hi Marek, 

In the directory where you have the fastback directory and your index.php file...

````
$ ls
fastback index.php
````

...try running: 

````
$ php ./index.php
job             | status            | updated             | percent_complete | last_completed      | 
--------------- | ----------------- | ------------------- | ---------------- | ------------------- | 
find_new_files  | Not queued        | 2024-05-31 20:00:18 |             100% | 2024-05-31 20:00:18 | 
make_csv        | Queued to run     | 2024-05-31 20:00:21 |             100% | 2024-05-31 20:00:21 | 
get_meta        | Not queued        | 2024-05-31 20:20:33 |             100% | 2024-05-31 20:20:33 | 
process_meta    | Not queued        | 2024-05-31 20:20:34 |             100% | 2024-05-31 20:20:34 | 
make_thumbs     | Queued to run     | 2024-05-31 19:00:18 |             100% | 2024-05-31 19:00:18 | 
make_webversion | Queued to run     | 2024-05-31 19:00:18 |             100% | 2024-05-31 19:00:18 | 
remove_deleted  | Currently Running | 2024-05-31 20:20:34 |             100% | 2024-05-31 19:00:15 | 
clear_locks     | Queued to run     | 2024-05-31 19:00:17 |             100% | 2024-05-31 19:00:17 | 
status          | Disabled          | 2024-05-31 20:20:31 |             100% | 2024-05-31 20:20:31 | 
````

It should output a table showing the different processes that need to happen to prepare and load photos. I'm running a development version, so your output may not match exactly. If you don't get output like this, please re-run with "debug" added and paste the output. 

````
$ php ./index.php debug
````

**Comment by marcza71** [comment]
Good morning. Unfortunately, it doesn't work, but it shows the error as below. PHP Version 8.2.12
I have: http://localhost/photos/
- fastback
-index.php

PHP Fatal error:  Uncaught Error: Call to undefined function pcntl_async_signals() in C:\xampp\htdocs\photos\fastback\fastback.php:341
Stack trace:
#0 C:\xampp\htdocs\photos\fastback\fastback.php(180): Fastback->util_handle_cli()
#1 C:\xampp\htdocs\photos\index.php(95): Fastback->run()
#2 {main}
thrown in C:\xampp\htdocs\photos\fastback\fastback.php on line 341

If I'm not boring you, please help. Thank you in advance. Greetings, Marek.
